baseURL = 'https://aleksandrgyumushyan.com/'
languageCode = 'en-us'
title = 'Aleksandr Gyumushyan'
theme = 'hugo-coder'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = true
    style = "monokai"


[caches]
  [caches.images]
    dir = ':cacheDir/images'


[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/aleksandrgyumushyan/"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 4
url = "https://github.com/AlexG28"

[[params.social]]
name = "Resume"
icon = "fa-solid fa-file-pdf fa-2x"
weight = 5
url = "/resume/main_resume_jake_.pdf"
       

[params]
  author = "Aleksandr Gyumushyan"
  description = "Aleksandr Gyumushyan's Personal Website"
  colorScheme = "auto"
  avatarURL = "images/avatar.jpg"
  customCSS = ["css/custom.css"]


[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "blog/"

[[languages.en.menu.main]]
name = "Photography"
weight = 3
url = "photography/"

